{$define UNIGUI_VCL}

{$ifndef UNIGUI_VCL}
library
{$else}
program
{$endif}
  OBSS;



uses
  uniGUIISAPI,
  Forms,
  ServerModuleEx in 'ServerModuleEx.pas' {UniServerModule: TUniGUIServerModule},
  MainModuleEx in 'MainModuleEx.pas' {UniMainModule: TUniGUIMainModule},
  MainMasterForm in '..\..\lib\ClientForm\MainMasterForm.pas' {MasterForm: TUniForm},
  MainFrameClass in '..\..\lib\ClientForm\MainFrameClass.pas' {FrameMainClass: TUniFrame},
  MainDataFormClass in '..\..\lib\ClientForm\MainDataFormClass.pas' {MainDataForm: TUniForm},
  MainGridFormClass in '..\..\lib\ClientForm\MainGridFormClass.pas' {MainGridForm: TUniForm},
  PopupMainClassForm in '..\..\lib\ClientForm\PopupMainClassForm.pas' {PopupMainClass},
  PsRcvNoDataForm in 'purchase\order\PsRcvNoDataForm.pas' {frmPsRcvNoPoData: TUniForm},
  PsAppPoDataForm in 'purchase\order\PsAppPoDataForm.pas' {frmPsAppPoData: TUniForm},
  PsAppPoGridForm in 'purchase\order\PsAppPoGridForm.pas' {frmPsAppPoGrid: TUniForm},
  PsApprCreditGridForm in 'purchase\order\PsApprCreditGridForm.pas' {frmPsApprCreditGrid: TUniForm},
  PsPoDataForm in 'purchase\order\PsPoDataForm.pas' {frmPsPoData: TUniForm},
  PsPoGridForm in 'purchase\order\PsPoGridForm.pas' {frmPsPoGrid: TUniForm},
  PsRcvByPoDataForm in 'purchase\order\PsRcvByPoDataForm.pas' {frmPsRcvByPoData: TUniForm},
  PsRcvByPoGridForm in 'purchase\order\PsRcvByPoGridForm.pas' {frmPsRcvByPoGrid: TUniForm},
  PsAppApprPaymentGridForm in 'purchase\payment\PsAppApprPaymentGridForm.pas' {frmPsAppApprPaymentGrid: TUniForm},
  PsAppApprPaymentDataForm in 'purchase\payment\PsAppApprPaymentDataForm.pas' {frmPsAppApprPaymentData: TUniForm},
  PsPaymentByAppGridForm in 'purchase\payment\PsPaymentByAppGridForm.pas' {frmPsPaymentByAppGrid: TUniForm},
  PsPaymentByAppDataForm in 'purchase\payment\PsPaymentByAppDataForm.pas' {frmPsPaymentByAppData: TUniForm},
  PsCashPaymentGridForm in 'purchase\payment\PsCashPaymentGridForm.pas' {frmPsCashPaymentGrid: TUniForm},
  PsCashPaymentDataForm in 'purchase\payment\PsCashPaymentDataForm.pas' {frmPsCashPaymentData: TUniForm},
  PsChequeClearingGridForm in 'purchase\payment\PsChequeClearingGridForm.pas' {frmPsChequeClearingGrid: TUniForm},
  ApInqGridForm in 'Ap\ApInqGridForm.pas' {frmApInqGrid: TUniForm},
  ApInqDataForm in 'Ap\ApInqDataForm.pas' {frmApInqData: TUniForm},
  SkRcvCarInMixerDataForm in 'stock\SkRcvCarInMixerDataForm.pas' {frmSkRcvCarInMixerData: TUniForm},
  PopupCarForm in 'stock\popup\PopupCarForm.pas' {PopupCar},
  SkOutCarFromMixerDataForm in 'stock\SkOutCarFromMixerDataForm.pas' {frmSkOutCarFromMixerData: TUniForm},
  SkRcvCarFromMixerDataForm in 'stock\SkRcvCarFromMixerDataForm.pas' {frmSkRcvCarFromMixerData: TUniForm},
  SkRcvCarFromComDataForm in 'stock\SkRcvCarFromComDataForm.pas' {frmSkRcvCarFromComData: TUniForm},
  SkMoveCarBetweenBrnDataForm in 'stock\SkMoveCarBetweenBrnDataForm.pas' {frmSkMoveCarBetweenBrnData: TUniForm},
  SkStockInqDataForm in 'stock\SkStockInqDataForm.pas' {frmSkStockInqData: TUniForm},
  SkStockInqForm in 'stock\SkStockInqForm.pas' {frmSkStockInq: TUniForm},
  CsAppSetupAccessoryForm in 'CarSale\Sale\CsAppSetupAccessoryForm.pas' {frmCsAppSetupAccessoryGrid: TUniForm},
  CsAppSetupAccessoryDataForm in 'CarSale\Sale\CsAppSetupAccessoryDataForm.pas' {frmCsAppSetupAccessoryData: TUniForm},
  CsApprSetupAccessoryDataForm in 'CarSale\Sale\CsApprSetupAccessoryDataForm.pas' {frmCsApprSetupAccessoryData: TUniForm},
  CsRcvMoneyAdvanceForm in 'CarSale\Sale\CsRcvMoneyAdvanceForm.pas' {frmCsRcvMoneyAdvanceGrid: TUniForm},
  CsRcvMoneyAdvanceDataForm in 'CarSale\Sale\CsRcvMoneyAdvanceDataForm.pas' {frmCsRcvMoneyAdvanceData: TUniForm},
  NSPurchaseOrderForm in 'NormalSale\NSPurchaseOrderForm.pas' {frmNsPurchaseOrderGrid: TUniForm},
  NsPurchaseOrderDataForm in 'NormalSale\NsPurchaseOrderDataForm.pas' {frmNsPurchaseOrderData: TUniForm},
  NSSentOrderForm in 'NormalSale\NSSentOrderForm.pas' {frmNsSentOrderGrid: TUniForm},
  NsSentOrderDataForm in 'NormalSale\NsSentOrderDataForm.pas' {frmNsSentOrderData: TUniForm},
  NSSentNoOrderForm in 'NormalSale\NSSentNoOrderForm.pas' {frmNsSentNoOrderGrid: TUniForm},
  NsSentNoOrderDataForm in 'NormalSale\NsSentNoOrderDataForm.pas' {frmNsSentNoOrderData: TUniForm},
  NSDebitCreditNoteForm in 'NormalSale\NSDebitCreditNoteForm.pas' {frmNsDebitCreditNoteGrid: TUniForm},
  NsDebitCreditNoteDataForm in 'NormalSale\NsDebitCreditNoteDataForm.pas' {frmNsSDebitCreditNoteData: TUniForm},
  RmReceiveMoneyDataForm in 'ReceiveMoney\RmReceiveMoneyDataForm.pas' {frmRmReceiveMoneyDataT: TUniForm},
  RmReceiveMoneyForm in 'ReceiveMoney\RmReceiveMoneyForm.pas' {frmRmReceiveMoneyGrid: TUniForm},
  RmReceiveDownDataForm in 'ReceiveMoney\RmReceiveDownDataForm.pas' {frmRmReceiveDownData: TUniForm},
  RmReceiveDownForm in 'ReceiveMoney\RmReceiveDownForm.pas' {frmRmReceiveDownGrid: TUniForm},
  RmCheqToBankDataForm in 'ReceiveMoney\RmCheqToBankDataForm.pas' {frmRmCheqToBankData: TUniForm},
  RmChangeNewCheqDataForm in 'ReceiveMoney\RmChangeNewCheqDataForm.pas' {frmRmChangeNewCheqData: TUniForm},
  RgGetMoneyPayForm in 'Registation\In\RgGetMoneyPayForm.pas' {frmRgGetMoneyPayGrid: TUniForm},
  RgGetMoneyPayDataForm in 'Registation\In\RgGetMoneyPayDataForm.pas' {frmRgGetMoneyPayData: TUniForm},
  RgSentMoneyPayForm in 'Registation\In\RgSentMoneyPayForm.pas' {frmRgSentMoneyPayGrid: TUniForm},
  RgSentMoneyPayDataForm in 'Registation\In\RgSentMoneyPayDataForm.pas' {frmRgSentMoneyPayData: TUniForm},
  RgInqRegistationDataForm in 'Registation\Out\RgInqRegistationDataForm.pas' {frmRgInqRegistationData: TUniForm},
  RrInqRedCardDataForm in 'RedRegistation\RrInqRedCardDataForm.pas' {frmRrInqRedCardData: TUniForm},
  SaAnalystInqForm in 'SaleAnalyst\SaAnalystInqForm.pas' {frmSaAnalystInq: TUniForm},
  MsSetupMoneyCodeForm in 'MoneySystem\MsSetupMoneyCodeForm.pas' {frmMsSetupMoneyCodeGrid: TUniForm},
  MsSetupMoneyCodetDataForm in 'MoneySystem\MsSetupMoneyCodetDataForm.pas' {frmMsSetupMoneyCodeData: TUniForm},
  MsSetupAccountTextDataForm in 'MoneySystem\MsSetupAccountTextDataForm.pas' {frmMsSetupAccountTextData: TUniForm},
  MsSetupLineSummarryDataForm in 'MoneySystem\MsSetupLineSummarryDataForm.pas' {frmMsSetupLineSummarryData: TUniForm},
  MsSetupLineSummarryForm in 'MoneySystem\MsSetupLineSummarryForm.pas' {frmMsSetupLineSummarryGrid: TUniForm},
  MsSetupCopyCancelCodeForm in 'MoneySystem\MsSetupCopyCancelCodeForm.pas' {frmMsSetupCopyCancelCodeGrid: TUniForm},
  MsSetupCopyCancelCodetDataForm in 'MoneySystem\MsSetupCopyCancelCodetDataForm.pas' {frmMsSetupCopyCancelCodeData: TUniForm},
  MsSelectCodeMoneyDataForm in 'MoneySystem\MsSelectCodeMoneyDataForm.pas' {frmMsSelectCodeMoneyData: TUniForm},
  MsChangeMoneyDataForm in 'MoneySystem\MsChangeMoneyDataForm.pas' {frmMsChangeMoneyData: TUniForm},
  MsSetupAccountTextForm in 'MoneySystem\MsSetupAccountTextForm.pas' {frmMsSetupAccountTextGrid: TUniForm},
  AsSetupOrgDataForm in 'AccountSystem\AsSetupOrgDataForm.pas' {frmAsSetupOrgData: TUniForm},
  AsSetupOrgForm in 'AccountSystem\AsSetupOrgForm.pas' {frmAsSetupOrgGrid: TUniForm},
  AsSetupAccDataForm in 'AccountSystem\AsSetupAccDataForm.pas' {frmAsSetupAccData: TUniForm},
  AsSetupAccForm in 'AccountSystem\AsSetupAccForm.pas' {frmAsSetupAccGrid: TUniForm},
  AsSetupAccOnBookDataForm in 'AccountSystem\AsSetupAccOnBookDataForm.pas' {frmAsSetupAccOnBookData: TUniForm},
  AsSetupAccOnBookForm in 'AccountSystem\AsSetupAccOnBookForm.pas' {frmAsSetupAccOnBookGrid: TUniForm},
  AsSetupTargetDataForm in 'AccountSystem\AsSetupTargetDataForm.pas' {frmAsSetupTargetData: TUniForm},
  AsSetupBBFDataForm in 'AccountSystem\AsSetupBBFDataForm.pas' {frmAsSetupBBFData: TUniForm},
  AsDocDailyDataForm in 'AccountSystem\AsDocDailyDataForm.pas' {frmAsDocDailyData: TUniForm},
  AsPopLinkSystemDataForm in 'AccountSystem\popup\AsPopLinkSystemDataForm.pas' {frmAsLinkSystemData: TUniForm},
  AsGLDataForm in 'AccountSystem\AsGLDataForm.pas' {frmAsGLData: TUniForm},
  AssAmtLostForm in 'AssetSystem\AssAmtLostForm.pas' {frmAssAmtLostGrid: TUniForm},
  AssSaleAssetDataForm in 'AssetSystem\AssSaleAssetDataForm.pas' {frmAssSaleAssetData: TUniForm},
  AssSaleAssetForm in 'AssetSystem\AssSaleAssetForm.pas' {frmAssSaleAssetGrid: TUniForm},
  AssSaleAssetLostDataForm in 'AssetSystem\AssSaleAssetLostDataForm.pas' {frmAssSaleAssetLostData: TUniForm},
  AssSaleAssetLostForm in 'AssetSystem\AssSaleAssetLostForm.pas' {frmAssSaleAssetLostGrid: TUniForm},
  AssUndefinedAssetDataForm in 'AssetSystem\AssUndefinedAssetDataForm.pas' {frmAssUndefinedAssetData: TUniForm},
  AssUndefinedAssetForm in 'AssetSystem\AssUndefinedAssetForm.pas' {frmAssUndefinedAssetGrid: TUniForm},
  AssMoveAssetBetweenBrnDataForm in 'AssetSystem\AssMoveAssetBetweenBrnDataForm.pas' {frmAssMoveAssetBetweenBrnData: TUniForm},
  AssMoveAssetBetweenBrnForm in 'AssetSystem\AssMoveAssetBetweenBrnForm.pas' {frmAssMoveAssetBetweenBrnGrid: TUniForm},
  TxTaxDataForm in 'TaxSystem\TaxSale\TxTaxDataForm.pas' {frmTxTaxData: TUniForm},
  TxTaxForm in 'TaxSystem\TaxSale\TxTaxForm.pas' {frmTxTaxGrid: TUniForm},
  TxChangeDescInTaxSaleForm in 'TaxSystem\TaxSale\TxChangeDescInTaxSaleForm.pas' {frmTxChangeDescInTaxSaleGrid: TUniForm},
  TxChangeDescInTaxBuyForm in 'TaxSystem\TaxBuy\TxChangeDescInTaxBuyForm.pas' {frmTxChangeDescInTaxBuyGrid: TUniForm},
  TxSelectSentTaxBuyForm in 'TaxSystem\TaxBuy\TxSelectSentTaxBuyForm.pas' {frmTxSelectSentTaxBuyGrid: TUniForm},
  TxSelectSentTaxSaleForm in 'TaxSystem\TaxSale\TxSelectSentTaxSaleForm.pas' {frmTxSelectSentTaxSaleGrid: TUniForm},
  TxChangeDocNoWHTForm in 'TaxSystem\WHT\TxChangeDocNoWHTForm.pas' {frmTxChangeDocNoWHTGrid: TUniForm},
  PopupAmtLostForm in 'AssetSystem\popup\PopupAmtLostForm.pas' {frmPopupAmtLost: TUniForm},
  PopupAddressForm in 'CarSale\Customer\popup\PopupAddressForm.pas' {PopupAddress: TUniForm},
  PopupCardForm in 'CarSale\Customer\popup\PopupCardForm.pas' {frmPopupCard: TUniForm},
  StDtlCodeForm in 'Setup\StDtlCodeForm.pas' {frmStDtlCodeGrid: TUniForm},
  StHdrCodeForm in 'Setup\StHdrCodeForm.pas' {frmStHdrCodeGrid: TUniForm},
  PopupStDtlCodeForm in 'Setup\popup\PopupStDtlCodeForm.pas' {frmPopupStDtlCode: TUniForm},
  PopupStHdrCodeForm in 'Setup\popup\PopupStHdrCodeForm.pas' {frmPopupStHdrCode: TUniForm},
  StRunningForm in 'Setup\StRunningForm.pas' {frmStRunningGrid: TUniForm},
  StRunningDataForm in 'Setup\StRunningDataForm.pas' {frmStRunningData: TUniForm},
  DSMainIntf in '..\..\lib\DSClientIntf\DSMainIntf.pas',
  DSMainIntfDM in '..\..\lib\DSClientIntf\DSMainIntfDM.pas' {DSMainDM: TDataModule},
  DSAuthorizedManagerIntf in '..\..\lib\DSClientIntf\DSAuthorizedManagerIntf.pas',
  DSAuthorizedManagerIntfDM in '..\..\lib\DSClientIntf\DSAuthorizedManagerIntfDM.pas' {DSAuthorizedManagerDM: TDataModule},
  ClientUtils in '..\..\lib\ClientUnit\ClientUtils.pas',
  XeUniGUIComponents in '..\..\lib\ClientUnit\XeUniGUIComponents.pas',
  PopupStNb1BrnGenDocForm in 'Setup\popup\PopupStNb1BrnGenDocForm.pas' {frmPopupStNb1BrnGenDoc: TUniForm},
  StApForm in 'Setup\StApForm.pas' {frmStApGrid: TUniForm},
  ArInqDataForm in 'Ar\ArInqDataForm.pas' {frmArInqData: TUniForm},
  ArInqGridForm in 'Ar\ArInqGridForm.pas' {frmArInqGrid: TUniForm},
  StArDataForm in 'Setup\StArDataForm.pas' {frmStArData: TUniForm},
  StArForm in 'Setup\StArForm.pas' {frmStArGrid: TUniForm},
  StProductForm in 'Setup\StProductForm.pas' {frmStProductGrid: TUniForm},
  StProductDataForm in 'Setup\StProductDataForm.pas' {frmStProductData: TUniForm},
  StTargetByProductDataForm in 'Setup\StTargetByProductDataForm.pas' {frmStTargetByProductData: TUniForm},
  StTargetByProductForm in 'Setup\StTargetByProductForm.pas' {frmStTargetByProductGrid: TUniForm},
  StTargetBySalemanDataForm in 'Setup\StTargetBySalemanDataForm.pas' {frmStTargetBySalemanData: TUniForm},
  StTargetBySalemanForm in 'Setup\StTargetBySalemanForm.pas' {frmStTargetBySaleManGrid: TUniForm},
  StFrameNoForm in 'Setup\StFrameNoForm.pas' {frmStFrameNoGrid: TUniForm},
  PopupArForm in '..\..\lib\popupForm\PopupArForm.pas' {frmPopupAr},
  StFrameNoDataForm in 'Setup\StFrameNoDataForm.pas' {frmStFrameNoData: TUniForm},
  PopupStAm3Form in 'Setup\popup\PopupStAm3Form.pas' {frmPopupStAm3: TUniForm},
  PopupProductForm in '..\..\lib\popupForm\PopupProductForm.pas' {frmPopupProduct},
  StCtShpForm in 'Setup\StCtShpForm.pas' {frmStCtShpGrid: TUniForm},
  StCtShpDataForm in 'Setup\StCtShpDataForm.pas' {frmStCtShpData: TUniForm},
  StCtCm3DataForm in 'Setup\StCtCm3DataForm.pas' {frmStCtCm3Data: TUniForm},
  StCtCm3Form in 'Setup\StCtCm3Form.pas' {frmStCtCm3Grid: TUniForm},
  StCtRm1Form in 'Setup\StCtRm1Form.pas' {frmStCtRm1Grid: TUniForm},
  StCtRm1DataForm in 'Setup\StCtRm1DataForm.pas' {frmStCtRm1Data: TUniForm},
  StMtRegForm in 'Setup\StMtRegForm.pas' {frmStMtRegGrid: TUniForm},
  StMtRegDataForm in 'Setup\StMtRegDataForm.pas' {frmStMtRegData: TUniForm},
  StMtRegExtraDataForm in 'Setup\StMtRegExtraDataForm.pas' {frmStMtRegExtraData: TUniForm},
  StArOvdAmtForm in 'Setup\StArOvdAmtForm.pas' {frmStArOvdAmtGrid: TUniForm},
  StArOvdAmtDataForm in 'Setup\StArOvdAmtDataForm.pas' {frmStArOvdAmtData: TUniForm},
  PopupStYm3Form in 'Setup\popup\PopupStYm3Form.pas' {frmPopupStYm3: TUniForm},
  StApOvdAmtForm in 'Setup\StApOvdAmtForm.pas' {frmStApOvdAmtGrid: TUniForm},
  StApOvdAmtDataForm in 'Setup\StApOvdAmtDataForm.pas' {frmStApOvdAmtData: TUniForm},
  PopupApForm in '..\..\lib\popupForm\PopupApForm.pas' {frmPopupAp},
  PopupAddrForm in 'Setup\popup\PopupAddrForm.pas' {frmPopupAddr},
  StStarttProductForm in 'Setup\StStarttProductForm.pas' {frmStStartProductGrid: TUniForm},
  StStartProductDataForm in 'Setup\StStartProductDataForm.pas' {frmStStartProductData: TUniForm},
  DSStockIntf in '..\..\lib\DSClientIntf\DSStockIntf.pas',
  DSSetupIntfDM in '..\..\lib\DSClientIntf\DSSetupIntfDM.pas' {DSSetupDM: TDataModule},
  DSPurchaseIntf in '..\..\lib\DSClientIntf\DSPurchaseIntf.pas',
  DSPurchaseIntfDM in '..\..\lib\DSClientIntf\DSPurchaseIntfDM.pas' {DSPurchaseDM: TDataModule},
  PsRcvProductNoPoForm in 'Purchase\order\PsRcvProductNoPoForm.pas' {frmPsRcvProductNoPoGrid: TUniForm},
  PsDebitCreditNoteDataForm in 'Purchase\order\PsDebitCreditNoteDataForm.pas' {frmPsDebitCreditNoteData: TUniForm},
  PsRcvProductNoPoDataForm in 'Purchase\order\PsRcvProductNoPoDataForm.pas' {frmPsRcvProductNoPoData: TUniForm},
  DSCarsaleIntf in '..\..\lib\DSClientIntf\DSCarsaleIntf.pas',
  DSCarsaleIntfDM in '..\..\lib\DSClientIntf\DSCarsaleIntfDM.pas' {DSCarsaleDM: TDataModule},
  CsCustomerDataForm in 'CarSale\Customer\CsCustomerDataForm.pas' {frmCsCustomerData: TUniForm},
  CsCustomerForm in 'CarSale\Customer\CsCustomerForm.pas' {frmCsCustomerGrid: TUniForm},
  PopupAc1Form in '..\..\lib\popupForm\PopupAc1Form.pas' {frmPopupAc1},
  PopupCsmForm in '..\..\lib\popupForm\PopupCsmForm.pas' {frmPopupCsm},
  CsAppSaleCarDataForm in 'CarSale\Sale\CsAppSaleCarDataForm.pas' {frmCsAppSaleCarData: TUniForm},
  CsAppSaleCarForm in 'CarSale\Sale\CsAppSaleCarForm.pas' {frmCsAppCarsaleGrid: TUniForm},
  PopupProductIM1Form in '..\..\lib\popupForm\PopupProductIM1Form.pas' {frmPopupProductIM1},
  PopupRCVCardForm in 'CarSale\Sale\popup\PopupRCVCardForm.pas' {frmPopupRCVCard: TUniForm},
  PopupExpForm in 'CarSale\Sale\popup\PopupExpForm.pas' {frmPopupExp: TUniForm},
  PopupAccessoryForm in 'CarSale\Sale\popup\PopupAccessoryForm.pas' {frmPopupAccessory: TUniForm},
  PopupProductByItcForm in '..\..\lib\popupForm\PopupProductByItcForm.pas' {frmPopupProductByItc},
  PopupDownForm in 'CarSale\Sale\popup\PopupDownForm.pas' {frmPopupDown: TUniForm},
  DSAssignWorkIntf in '..\..\lib\DSClientIntf\DSAssignWorkIntf.pas',
  DSAssignWorkIntfDM in '..\..\lib\DSClientIntf\DSAssignWorkIntfDM.pas' {DSAssignWorkDM: TDataModule},
  PopupWeekForm in 'AssignWork\popup\PopupWeekForm.pas' {frmPopupWeek: TUniForm},
  PopupMarkFlagForm in 'AssignWork\popup\PopupMarkFlagForm.pas' {frmPopupWorkFlag: TUniForm},
  AWRundownTMTForm in 'AssignWork\AWRundownTMTForm.pas' {frmAWRundownTMTGrid: TUniForm},
  AWSetupCalendaForm in 'AssignWork\AWSetupCalendaForm.pas' {frmAWSetupCalendaGrid: TUniForm},
  AWRundownTMTCalendaForm in 'AssignWork\AWRundownTMTCalendaForm.pas' {frmAWRundownTMTCalendaGrid: TUniForm},
  PopupRunDownForm in 'AssignWork\popup\PopupRunDownForm.pas' {frmPopupRunDown: TUniForm},
  AWPreAssignForm in 'AssignWork\AWPreAssignForm.pas' {frmAWPreAssignGrid: TUniForm},
  AWPreAssignCalendaForm in 'AssignWork\AWPreAssignCalendaForm.pas' {frmAWPreAssignCalendaGrid: TUniForm},
  PopupPreAssignForm in 'AssignWork\popup\PopupPreAssignForm.pas' {frmPopupPreAssign},
  AWAssignNoWeekForm in 'AssignWork\AWAssignNoWeekForm.pas' {frmAWAssignNoWeekGrid: TUniForm},
  AWAssignNoWeekCalendaForm in 'AssignWork\AWAssignNoWeekCalendaForm.pas' {frmAWAssignNoWeekCalendaGrid: TUniForm},
  PopupAssignNoWeekForm in 'AssignWork\popup\PopupAssignNoWeekForm.pas' {frmPopupAssignNoWeek},
  MainPopupDataFormClass in '..\..\lib\ClientForm\MainPopupDataFormClass.pas' {MainPopupDataForm: TUniForm},
  PopupAssignWeekForm in 'AssignWork\popup\PopupAssignWeekForm.pas' {frmPopupAssignWeek},
  AWAssignWeekCalendaForm in 'AssignWork\AWAssignWeekCalendaForm.pas' {frmAWAssignWeekCalendaGrid: TUniForm},
  AWAssignWeekForm in 'AssignWork\AWAssignWeekForm.pas' {frmAWAssignWeekGrid: TUniForm},
  AWOrderColCalendaForm in 'AssignWork\AWOrderColCalendaForm.pas' {frmAWOrderColCalendaGrid: TUniForm},
  AWOrderColForm in 'AssignWork\AWOrderColForm.pas' {frmAWOrderColGrid: TUniForm},
  PopupOrderColForm in 'AssignWork\popup\PopupOrderColForm.pas' {frmPopupOrderCol},
  AWAssignOutCalendaForm in 'AssignWork\AWAssignOutCalendaForm.pas' {frmAWAssignOutCalendaGrid: TUniForm},
  AWAssignOutForm in 'AssignWork\AWAssignOutForm.pas' {frmAWAssignOutGrid: TUniForm},
  AWAssignPersonalForm in 'AssignWork\AWAssignPersonalForm.pas' {frmAWAssignPersonalGrid: TUniForm},
  AWAssignPersonalCalendaForm in 'AssignWork\AWAssignPersonalCalendaForm.pas' {frmAWAssignPersonalCalendaGrid: TUniForm},
  frmMainMenusForm in 'menu\frmMainMenusForm.pas' {frmMainMemus: TUniForm},
  DSReceiveMoneyIntf in '..\..\lib\DSClientIntf\DSReceiveMoneyIntf.pas',
  DSReceiveMoneyIntfDM in '..\..\lib\DSClientIntf\DSReceiveMoneyIntfDM.pas' {DSReceiveMoneyDM: TDataModule},
  PopupRcvMoneyForm in 'ReceiveMoney\popup\PopupRcvMoneyForm.pas' {frmPopupRcvMoney: TUniForm},
  PopupRcvAm4Form in 'ReceiveMoney\popup\PopupRcvAm4Form.pas' {frmPopupRcvAm4: TUniForm},
  PopupRedCardForm in '..\..\lib\popupForm\PopupRedCardForm.pas' {frmPopupRedCard},
  RrGetAdvanceMoneyForm in 'RedRegistation\RrGetAdvanceMoneyForm.pas' {frmRrGetAdvanceMoneyGrid: TUniForm},
  RrGetAdvanceMoneyDataForm in 'RedRegistation\RrGetAdvanceMoneyDataForm.pas' {frmRrGetAdvanceMoneyData: TUniForm},
  DSRegistationIntf in '..\..\lib\DSClientIntf\DSRegistationIntf.pas',
  DSRegistationIntfDM in '..\..\lib\DSClientIntf\DSRegistationIntfDM.pas' {DSRegistationDM: TDataModule},
  PopupAdvanceYm4Form in 'RedRegistation\popup\PopupAdvanceYm4Form.pas' {frmPopupAdvanceYm4: TUniForm},
  RrReturnMoneyRedCardForm in 'RedRegistation\RrReturnMoneyRedCardForm.pas' {frmRrReturnMoneyRedCardGrid: TUniForm},
  RrReturnMoneyRedCardDataForm in 'RedRegistation\RrReturnMoneyRedCardDataForm.pas' {frmRrReturnMoneyRedCardData: TUniForm},
  PopupAdvanceAm6Form in 'RedRegistation\popup\PopupAdvanceAm6Form.pas' {frmPopupAdvanceAm6: TUniForm},
  PopupAdvanceForReturnForm in 'RedRegistation\popup\PopupAdvanceForReturnForm.pas' {frmPopupAdvanceForReturn},
  RgRegistationToOutForm in 'Registation\Out\RgRegistationToOutForm.pas' {frmRgRegistationToOutGrid: TUniForm},
  PopupRegistationOm5Form in 'Registation\popup\PopupRegistationOm5Form.pas' {frmPopupRegistationOm5: TUniForm},
  RgRegistationToOutDataForm in 'Registation\Out\RgRegistationToOutDataForm.pas' {frmRgRegistationToOutData: TUniForm},
  RgRegistationFromOutForm in 'Registation\Out\RgRegistationFromOutForm.pas' {frmRgRegistationFromOutGrid: TUniForm},
  PopupRegistationRg1ListForRg2Form in 'Registation\popup\PopupRegistationRg1ListForRg2Form.pas' {frmPopupRegistationRg1ListForRg2},
  PopupRegistationRg1Form in 'Registation\popup\PopupRegistationRg1Form.pas' {frmPopupRegistationRg1: TUniForm},
  RgRegistationFromOutDataForm in 'Registation\Out\RgRegistationFromOutDataForm.pas' {frmRgRegistationFromOutData: TUniForm},
  PopupRegistationFromOutForm in 'Registation\popup\PopupRegistationFromOutForm.pas' {frmPopupRegistationFromOutForm: TUniForm},
  RgRegistationBookFromOutForm in 'Registation\Out\RgRegistationBookFromOutForm.pas' {frmRgRegistationBookFromOutGrid: TUniForm},
  RgRegistationBookFromOutDataForm in 'Registation\Out\RgRegistationBookFromOutDataForm.pas' {frmRgRegistationBookFromOutData: TUniForm},
  PopupRegistationRg2ListForBookForm in 'Registation\popup\PopupRegistationRg2ListForBookForm.pas' {frmPopupRegistationRg2ListForBook},
  PopupRegistationRg2Form in 'Registation\popup\PopupRegistationRg2Form.pas' {frmPopupRegistationRg2: TUniForm},
  PsRcvProductCarDataForm in 'Purchase\order\PsRcvProductCarDataForm.pas' {frmPsRcvProductCarData: TUniForm},
  PsRcvProductCarForm in 'Purchase\order\PsRcvProductCarForm.pas' {frmPsRcvProductCarGrid: TUniForm},
  PopupAssignWeekOutForm in 'Purchase\popup\PopupAssignWeekOutForm.pas' {frmPopupAssignWeekOut},
  PopupApplicationForm in '..\..\lib\popupForm\PopupApplicationForm.pas' {frmPopupApplication},
  MainReportForm in '..\..\lib\ClientForm\MainReportForm.pas' {MainReportFrm: TUniForm},
  MainPrintForm in '..\..\lib\ClientForm\MainPrintForm.pas' {MainPrint},
  CsApprSaleCarForm in 'CarSale\Sale\CsApprSaleCarForm.pas' {frmCsApprSaleCarGrid: TUniForm},
  CsApprSaleCarDataForm in 'CarSale\Sale\CsApprSaleCarDataForm.pas' {frmCsApprSaleCarData: TUniForm},
  PsDebitCreditNoteGridForm in 'Purchase\order\PsDebitCreditNoteGridForm.pas' {FrmPsDebitCreditNoteGrid: TUniForm},
  PaAnalystInqGridForm in 'BuyAnalyst\PaAnalystInqGridForm.pas' {frmPaAnalystInqGrid: TUniForm},
  SaAnalystInqGridForm in 'SaleAnalyst\SaAnalystInqGridForm.pas' {frmSaAnalystInqGrid: TUniForm},
  RrReceiveMoneyDataForm in 'RedRegistation\RrReceiveMoneyDataForm.pas' {frmRrReceiveMoneyDataT: TUniForm},
  RrReceiveMoneyForm in 'RedRegistation\RrReceiveMoneyForm.pas' {frmRrReceiveMoneyGrid: TUniForm},
  PopupRedRegRcvAm4Form in 'RedRegistation\redreg_popup\PopupRedRegRcvAm4Form.pas' {frmPopupRedRegRcvAm4: TUniForm},
  PopupRedRegRcvMoneyForm in 'RedRegistation\redreg_popup\PopupRedRegRcvMoneyForm.pas' {frmPopupRedRegRcvMoney: TUniForm},
  PsAssignOutGridForm in 'Purchase\order\PsAssignOutGridForm.pas' {frmPsAssignOutGrid: TUniForm},
  PsAssignOutForm in 'Purchase\order\PsAssignOutForm.pas' {frmPsAssignOutData: TUniForm},
  StApDataForm in 'Setup\StApDataForm.pas' {frmStApData: TUniForm},
  StFg1Form in 'Setup\StFg1Form.pas' {frmStFg1Grid: TUniForm},
  StFg1DataForm in 'Setup\StFg1DataForm.pas' {frmStFg1Data: TUniForm},
  PopupFg1Form in 'Setup\popup\PopupFg1Form.pas' {frmPopupFg1: TUniForm},
  PopupFg1ListForm in '..\..\lib\popupForm\PopupFg1ListForm.pas' {frmPopupFg1List},
  DSSetupIntf in '..\..\lib\DSClientIntf\DSSetupIntf.pas',
  DSStockIntfDM in '..\..\lib\DSClientIntf\DSStockIntfDM.pas' {DSStockDM: TDataModule},
  TtStockForm in 'stocks\TtStockForm.pas' {frmTtStockGrid: TUniForm};

{$R *.res}

{$ifndef UNIGUI_VCL}
exports
  GetExtensionVersion,
  HttpExtensionProc,
  TerminateExtension;
{$endif}

begin
{$ifdef UNIGUI_VCL}
  Application.Initialize;
  TUniServerModule.Create(Application);
  Application.Run;
{$endif}
end.
