  SELECT distinct aloha_person.hospcode,   
         aloha_person.cid,   
         aloha_person.pid,   
         aloha_person.hid,   
         trim(aloha_person.prename) as prename,   
         trim(aloha_person.name) as name,   
         trim(aloha_person.lname) as lname,   
         aloha_person.hn,   
         aloha_person.sex,   
         aloha_person.birth - 5430000 as birth,   
         aloha_person.mstatus,   
         aloha_person.occupation_old,   
         aloha_person.occupation_new,   
         aloha_person.race,   
         aloha_person.nation,   
         aloha_person.religion,   
         aloha_person.education,   
         aloha_person.fstatus,   
         aloha_person.father,   
         aloha_person.mother,   
         aloha_person.couple,   
         aloha_person.vstatus,   
         aloha_person.movein,   
         aloha_person.discharge,   
         aloha_person.ddischarge,   
         aloha_person.abogroup,   
         aloha_person.rhgroup,   
         aloha_person.labor,   
         aloha_person.passport,   
         aloha_person.typearea,   
         max(aloha_person.d_update)  - 5430000000000 as d_update
    FROM aloha_person  where aloha_person.export between 25571121 and 25571131
and aloha_person.pid>1
group by
aloha_person.hospcode,   
         aloha_person.cid,   
         aloha_person.pid,   
         aloha_person.hid,   
         aloha_person.prename,   
         aloha_person.name,   
         aloha_person.lname,   
         aloha_person.hn,   
         aloha_person.sex,   
         aloha_person.birth,   
         aloha_person.mstatus,   
         aloha_person.occupation_old,   
         aloha_person.occupation_new,   
         aloha_person.race,   
         aloha_person.nation,   
         aloha_person.religion,   
         aloha_person.education,   
         aloha_person.fstatus,   
         aloha_person.father,   
         aloha_person.mother,   
         aloha_person.couple,   
         aloha_person.vstatus,   
         aloha_person.movein,   
         aloha_person.discharge,   
         aloha_person.ddischarge,   
         aloha_person.abogroup,   
         aloha_person.rhgroup,   
         aloha_person.labor,   
         aloha_person.passport,   
         aloha_person.typearea ;
