unit DSServerConstant;

interface

const

  _MS_SQL_CONNECTION_STRING_ =
    'Provider=SQLOLEDB.1;Password=%s;Persist Security Info=True;User ID=%s;Initial Catalog=%s;Data Source=%s';

  _DS_LIFE_CYCLE_LIST_: array[0..2] of UnicodeString = (
    'Invocation', 'Server', 'Session');

{$IFDEF MSSQL_DIALECT}
  _CONFIG_FILE_ = 'dsConfigsvrX64.conf';
  _LOG_FILE_ = 'dsConfigsvrX64.log';
{$ELSE}
  _CONFIG_FILE_ = 'dsconfigsvr.conf';
  _LOG_FILE_ = 'dsconfigsvr.log';
{$ENDIF}

  _APPSVR_EVENT_ = 'APPSVR_EVENT';
  _SYSTEM_ = 'SYSTEM';
  _LOCALHOST_ = 'LOCALHOST';
  _NULL_STR_ = '';

  {* Miscelaneous and Error Message *}
  _DATE_TIME_FORMATE_ = 'mmmm dd, yyyy hh:mm:ss.zzz';

  _SVR_CREATED_ = 'Server module %s has been created.';
  _SVR_DESTROYED_ = 'Server module %s has been destroyed.';

  _LOG_MSG_FORMAT_ = '(IP: %s, BranchCode: %s, UserID: %s) - %s';

  {********* Error Message *********}
  _ERR_ON_METHOD_ = 'Error on %s.%s: %s';
  _ERR_NOT_LOGGED_IN_ = 'Client application try to used server without logged in';
  _ERR_RAISED_NOT_LOGGED_IN_ = 'You''re not logged-in into this Application Server';

  _ERR_ALREADY_LOGGED_IN_ = 'Error: This session has been logged-in since %s.';

  _ERR_UPDATE_SESSION_CALL_ = 'call UpdateSession() error: %s';
  _ERR_PROCEDURE_CALL_ = 'Calling to method: %s.%s was error with message: %s';

  _ERROR_UNDEFINED_ = 9999999;

  _NO_ERROR_ = 0;

  {* SQL Constant *}
  _CR_ = #10#13;
  _CM_ = ', ' + _CR_;
  _CL_ = ':';
  _BKO_ = '(';
  _BKC_ = ')';
  _SELECT_ = 'SELECT' + _CR_;
  _FROM_ = 'FROM' + _CR_;
  _WHERE_ = 'WHERE' + _CR_;
  _AND_ = 'AND';
  _OR_ = 'OR';
  _EQ_ = ' = ';

  _RESULT_ = 'RESULT';
  _COMPANY_CODE_ = 'COMPANY_CODE';
  _COMPANY_ORG_CODE_ = 'COMPANY_ORG_CODE';
  _COMPANY_NAME_ = 'COMPANY_NAME';
  _BRANCH_CODE_ = 'BRANCH_CODE';
  _BRANCH_ORG_CODE_ = 'BRANCH_ORG_CODE';
  _BRANCH_NAME_ = 'BRANCH_NAME';
  _USER_TYPE_= 'USER_TYPE';
  _USER_ID_= 'USER_ID';
  _USER_PWD_ = 'USER_PWD';
  _USER_NAME_ = 'USER_NAME';
  _DESCRIPTION_ = 'DESCRIPTION';
  _LOAN_TYPE_ = 'LOAN_TYPE';
  _CONTRACT_ID_ = 'CONTRACT_ID';
  _CONTRACT_NO_ = 'CONTRACT_NO';
  _CONTRACT_STS_ = 'CONTRACT_STS';
  _PASSWORD_ = 'PASSWORD';
  _NUMBER_OF_DAYS_BEFORE_EXPIRED_ = 'NUMBER_OF_DAYS_BEFORE_EXPIRED';
  _LAST_SIGNED_ON_DATE_ = 'LAST_SIGNED_ON_DATE';

  _ITEM_ = 'ITEM';
  _AMT_REMAIN_ = 'AMT_REMAIN';
  _AMT_ = 'AMT';
  _AMOUNT_ = 'AMOUNT';

  _UID_= 'UID';
  _PWD_ = 'PWD';

  _FLAG_ = 'FLAG';
  _ACTIVE_ = 'A';
  _INACTIVE_ = 'I';

  _PARENT_ID_ = 'PARENT_ID';
  _RECORD_ID_ = 'RECORD_ID';
  _IS_INSERT_ = 'IS_INSERT';
  _ROLE_ID_ = 'ROLE_ID';
  _LANG_ID_ = 'LANG_ID';
  _REF_TEYP_ = 'REF_TYPE';

  _FULL_TEXT_SEARCH_ = 'FT_CRITERIA';
  _SEARCH_MODE_ = 'FT_SEARCH_MODE';
  _ORDER_FIELD_ = 'ORDER_FIELD';

  _SEARCH_MODE_ALL_ = 0;
  _SEARCH_MODE_SPECIFIED_ = 1;

  _SP_PARAM_PARENT_ID_ = _PARENT_ID_;
  _SP_PARAM_RECORD_ID_ = _RECORD_ID_;
  _SP_PARAM_USER_NAME_ = _USER_NAME_;
  _SP_PARAM_USER_ID_ = _USER_ID_;
  _SP_PARAM_PASSWORD_ = _PASSWORD_;
  _SP_PARAM_LANG_ID_ = _LANG_ID_;
  _SP_PARAM_DESCRIPTION_ = _DESCRIPTION_;
  _SP_PARAM_RESULT_ = _RESULT_;
  _SP_PARAM_COMPANY_CODE_ = _COMPANY_CODE_;
  _SP_PARAM_COMPANY_ORG_CODE_ = _COMPANY_ORG_CODE_;
  _SP_PARAM_COMPANY_NAME_ = _COMPANY_NAME_;
  _SP_PARAM_BRANCH_CODE_ = _BRANCH_CODE_;
  _SP_PARAM_BRANCH_ORG_CODE_ = _BRANCH_ORG_CODE_;
  _SP_PARAM_BRANCH_NAME_ = _BRANCH_NAME_;
  _SP_PARAM_LOAN_TYPE_ = _LOAN_TYPE_;
  _SP_PARAM_CONTRACT_ID_ = _CONTRACT_ID_;
  _SP_PARAM_CONTRACT_NO_ = _CONTRACT_NO_;
  _SP_PARAM_CONTRACT_STS_ = _CONTRACT_STS_;
  _SP_PARAM_ID_ = 'ID';
  _SP_PARAM_FLAG_ = _FLAG_;
  _SP_PARAM_REF_TEYP_ =  _REF_TEYP_;
  _SP_PARAM_FULL_TEXT_SEARCH_ = _FULL_TEXT_SEARCH_;
  _SP_PARAM_SEARCH_MODE_ = _SEARCH_MODE_;
  _SP_PARAM_ORDER_FIELD_ = _ORDER_FIELD_;

  _SP_PARAM_UID_= _UID_;
  _SP_PARAM_PWD_ = _PWD_;
  _SP_PARAM_ITEM_ = _ITEM_;
 _SP_PARAM_NUMBER_OF_DAYS_BEFORE_EXPIRED_ = _NUMBER_OF_DAYS_BEFORE_EXPIRED_;
  _SP_PARAM_LAST_SIGNED_ON_DATE_ = _LAST_SIGNED_ON_DATE_;


  _SP_PARAM_IS_INSERT_ = _IS_INSERT_;

  _REC_COUNT_ = 'REC_COUNT';
  _SP_PARAM_REC_COUNT_ = _REC_COUNT_;

  _ROWS_FROM_ = 'ROWS_FROM';
  _ROWS_TO_ = 'ROWS_TO';
  _SPECIFIC_CRITERIA_ = 'SPECIFIC_CRITERIA';
  _SP_ROWS_FROM_ = _ROWS_FROM_;
  _SP_ROWS_TO_ = _ROWS_TO_;
  _SP_PARAM_SPECIFIC_CRITERIA_ = _SPECIFIC_CRITERIA_;

  _IPARAM_TO_DATE = 'IPARAM_TO_DATE';
  _SP_PARAM_IPARAM_TO_DATE = _IPARAM_TO_DATE;

  _SP_PARAM_AMT_REMAIN_ = _AMT_REMAIN_;
  _SP_PARAM_AMT_ = _AMT_;
  _SP_PARAM_AMOUNT_ = _AMOUNT_;

{$IFDEF MSSQL_DIALECT}
  _SP_LOG_INS_ = 'EXEC SP_LOG_INS(''%s'')';
{$ELSE}
  _SP_LOG_INS_ = 'EXECUTE PROCEDURE SP_LOG_INS(''%s'')';
{$ENDIF}

  _SP_ERR_MSG_ = 'SELECT RESULT FROM SP_MESSAGE_GET_ERROR(%d, %d)';
  {****************************************************************************}
  _SP_GET_TEXT_DESC_ = 'SELECT * FROM SP_DESC_GET_LIST(:CODE, :FLAG, :LANG_ID)';

  {****************************************************************************}
  { CIF Constants.                                                             }
  {****************************************************************************}

  {***** Parameter for SP_CIF_JURISTIC_SET_INFO & SP_CIF_PERSONAL_SET_INFO *****}
  {***** CIF Main Info Fields *****}
  _CIF_ID_ = 'CIF_ID';
  _CIF_REG_DATE_ = 'CIF_REG_DATE';
  _REF_TYPE_ = 'REF_TYPE';
  _CIF_GROUP_ = 'CIF_GROUP';
  _CIF_TYPE_ = 'CIF_TYPE';
  _CIF_SUB_TYPE_ = 'CIF_SUB_TYPE';
  _CIF_NO_ = 'CIF_NO';
  _CIF_STATUS_ = 'CIF_STATUS';
  _CIF_BOT_TYPE_ = 'CIF_BOT_TYPE';
  _LAST_SCORE_RATING_ = 'LAST_SCORE_RATING';
  _TITLE_NAME_TH_ = 'TITLE_NAME_TH';
  _FIRST_NAME_THA_ = 'FIRST_NAME_THA';
  _LAST_NAME_THA_ = 'LAST_NAME_THA';
  _TITLE_NAME_EN_ = 'TITLE_NAME_EN';
  _FIRST_NAME_ENG_ = 'FIRST_NAME_ENG';
  _LAST_NAME_ENG_ = 'LAST_NAME_ENG';
  _REF_NO_ = 'REF_NO';
  _REF_NO_TYPE_ = 'REF_NO_TYPE';
  _REF_NO_ISSUED_DATE_ = 'REF_NO_ISSUED_DATE';
  _REF_NO_EXPIRED_DATE_ = 'REF_NO_EXPIRED_DATE';
  _REF_NO_ISSUED_AT_ = 'REF_NO_ISSUED_AT';
  _RELATION_WITH_FINANCE_ = 'RELATION_WITH_FINANCE';
  _REF_BANK_ACC_CODE_ = 'REF_BANK_ACC_CODE';
  _CONTACT_DATE_ = 'CONTACT_DATE';
  _RISK_BUSSINESS_TYPE_ = 'RISK_BUSSINESS_TYPE';
  _RELATED_WITH_POLITICIAN_ = 'RELATED_WITH_POLITICIAN';
  _CORE_BANK_REF_NO_ = 'CORE_BANK_REF_NO';

  {***** Juristic Info Fields *****}
  _MAIN_BUSINESS_TYPE_ = 'MAIN_BUSINESS_TYPE';
  _SPECIFIED_BUSINESS_TYPE_ = 'SPECIFIED_BUSINESS_TYPE';
  _CONTACT_PERSON_NAME_ = 'CONTACT_PERSON_NAME';
  _CONTACT_PERSON_TEL_NO_ = 'CONTACT_PERSON_TEL_NO';
  _REG_CAP_ALL_ = 'REG_CAP_ALL';
  _REG_CAP_PAID_ = 'REG_CAP_PAID';
  _REG_DATE_ = 'REG_DATE';
  _REG_NATIONALITY_ = 'REG_NATIONALITY';
  _TAX_ID_ = 'TAX_ID';
  _ANNUAL_YEAR_ = 'ANNUAL_YEAR';
  _ANNUAL_INC_AMT_ = 'ANNUAL_INC_AMT';
  _ANNUAL_INC_OTH_AMT_ = 'ANNUAL_INC_OTH_AMT';
  _ANNUAL_EXPENSE_AMT_ = 'ANNUAL_EXPENSE_AMT';
  _ANNUAL_EXPENSE_OTH_AMT_ = 'ANNUAL_EXPENSE_OTH_AMT';
  _ANNUAL_DEBT_AMT_ = 'ANNUAL_DEBT_AMT';
  _ANNUAL_PROFIT_AMT_ = 'ANNUAL_PROFIT_AMT';
  _EMPLOYEE_TOTAL_NO_ = 'EMPLOYEE_TOTAL_NO';
  _REF_DOC_NO_ = 'REF_DOC_NO';
  _REF_DOC_DATE_ = 'REF_DOC_DATE';
  _REF_ISSUE_BY_ = 'REF_ISSUE_BY';
  _EMAIL_ADDRESS_ = 'EMAIL_ADDRESS';
  _REAL_ESTATE_LAND_AMT_ = 'REAL_ESTATE_LAND_AMT';
  _REAL_ESTATE_OTH_AMT_ = 'REAL_ESTATE_OTH_AMT';
  _PD_GRADE_SCORE_ = 'PD_GRADE_SCORE';
  _PD_GRADE_INIT_SCORE_DATE_ = 'PD_GRADE_INIT_SCORE_DATE';
  _PD_GRADE_REVISED_SCORE_DATE_ = 'PD_GRADE_REVISED_SCORE_DATE';
  _REG_IN_STOCK_EXCHANGE_MARKET_ = 'REG_IN_STOCK_EXCHANGE_MARKET';
  _MOST_INCOME_IN_CASH_ = 'MOST_INCOME_IN_CASH';

  {***** Personal Info Fields *****}
  _PERSON_LEGAL_TYPE_ = 'PERSON_LEGAL_TYPE';
  _CITIZENSHIP_ = 'CITIZENSHIP';
  _NATIONALITY_ = 'NATIONALITY';
  _BIRTH_DATE_ = 'BIRTH_DATE';
  _GENDER_ = 'GENDER';
  _EDUCATION_ = 'EDUCATION';
  _MARRIED_STATUS_ = 'MARRIED_STATUS';
  _OCCUPATION_ = 'OCCUPATION';
  _WORK_PLACE_ = 'WORK_PLACE';
  _WORK_TYPE_ = 'WORK_TYPE';
  _JOB_POSITION_ = 'JOB_POSITION';
  _WORK_BUS_TYPE_ = 'WORK_BUS_TYPE';
  _CONTACT_PERSON_TITLE_NAME_ = 'CONTACT_PERSON_TITLE_NAME';
  _CONTACT_PERSON_FIRST_NAME_ = 'CONTACT_PERSON_FIRST_NAME';
  _CONTACT_PERSON_LAST_NAME_ = 'CONTACT_PERSON_LAST_NAME';
  _CONTACT_PERSON_RELATION_ = 'CONTACT_PERSON_RELATION';
  _CONTACT_PERSON_MOBILE_PHONE_ = 'CONTACT_PERSON_MOBILE_PHONE';
  _MOBILE_NO_ = 'MOBILE_NO';
  //_EMAIL_ADDRESS_ = 'EMAIL_ADDRESS';
  _HAS_NAME_CHANGED_HISTORY_ = 'HAS_NAME_CHANGED_HISTORY';
  _NAME_CHANGED_REASON_ = 'NAME_CHANGED_REASON';

  {***** Co-operated fields *****}
  _NOTE_ = 'NOTE';
  _NEW_CIF_ID_ = 'NEW_CIF_ID';
  _NEW_CIF_NO_ = 'NEW_CIF_NO';
  _NEW_ACCOUNT_ID_ = 'NEW_ACCOUNT_ID';
  _ACCOUNT_ID_ = 'ACCOUNT_ID';

  {***** CIF Main Info params *****}
  _SP_PARAM_CIF_ID_ = _CIF_ID_;
  _SP_PARAM_CIF_REG_DATE_ = _CIF_REG_DATE_;
  _SP_PARAM_REF_TYPE_ = _REF_TYPE_;
  _SP_PARAM_CIF_GROUP_ = _CIF_GROUP_;
  _SP_PARAM_CIF_TYPE_ = _CIF_TYPE_;
  _SP_PARAM_CIF_SUB_TYPE_ = _CIF_SUB_TYPE_;
  _SP_PARAM_CIF_NO_ = _CIF_NO_;
  _SP_PARAM_CIF_STATUS_ = _CIF_STATUS_;
  _SP_PARAM_CIF_BOT_TYPE_ = _CIF_BOT_TYPE_;
  _SP_PARAM_LAST_SCORE_RATING_ = _LAST_SCORE_RATING_;
  _SP_PARAM_TITLE_NAME_TH_ = _TITLE_NAME_TH_;
  _SP_PARAM_FIRST_NAME_THA_ = _FIRST_NAME_THA_;
  _SP_PARAM_LAST_NAME_THA_ = _LAST_NAME_THA_;
  _SP_PARAM_TITLE_NAME_EN_  = _TITLE_NAME_EN_;
  _SP_PARAM_FIRST_NAME_ENG_ = _FIRST_NAME_ENG_;
  _SP_PARAM_LAST_NAME_ENG_ = _LAST_NAME_ENG_;
  _SP_PARAM_REF_NO_ = _REF_NO_;
  _SP_PARAM_REF_NO_TYPE_ = _REF_NO_TYPE_;
  _SP_PARAM_REF_NO_ISSUED_DATE_ = _REF_NO_ISSUED_DATE_;
  _SP_PARAM_REF_NO_EXPIRED_DATE_ = _REF_NO_EXPIRED_DATE_;
  _SP_PARAM_REF_NO_ISSUED_AT_ = _REF_NO_ISSUED_AT_;
  _SP_PARAM_RELATION_WITH_FINANCE_ = _RELATION_WITH_FINANCE_;
  _SP_PARAM_REF_BANK_ACC_CODE_ = _REF_BANK_ACC_CODE_;
  _SP_PARAM_CONTACT_DATE_ = _CONTACT_DATE_;
  _SP_PARAM_RISK_BUSSINESS_TYPE_ = _RISK_BUSSINESS_TYPE_;
  _SP_PARAM_RELATED_WITH_POLITICIAN_ = _RELATED_WITH_POLITICIAN_;
  _SP_PARAM_CORE_BANK_REF_NO_ = _CORE_BANK_REF_NO_;

  {***** Juristic Info params *****}
  _SP_PARAM_MAIN_BUSINESS_TYPE_ = _MAIN_BUSINESS_TYPE_;
  _SP_PARAM_SPECIFIED_BUSINESS_TYPE_ = _SPECIFIED_BUSINESS_TYPE_;
  _SP_PARAM_CONTACT_PERSON_NAME_ = _CONTACT_PERSON_NAME_;
  _SP_PARAM_CONTACT_PERSON_TEL_NO_ = _CONTACT_PERSON_TEL_NO_;
  _SP_PARAM_REG_CAP_ALL_ = _REG_CAP_ALL_;
  _SP_PARAM_REG_CAP_PAID_ = _REG_CAP_PAID_;
  _SP_PARAM_REG_DATE_ = _REG_DATE_;
  _SP_PARAM_REG_NATIONALITY_ = _REG_NATIONALITY_;
  _SP_PARAM_TAX_ID_ = _TAX_ID_;
  _SP_PARAM_ANNUAL_YEAR_ = _ANNUAL_YEAR_;
  _SP_PARAM_ANNUAL_INC_AMT_ = _ANNUAL_INC_AMT_;
  _SP_PARAM_ANNUAL_INC_OTH_AMT_ = _ANNUAL_INC_OTH_AMT_;
  _SP_PARAM_ANNUAL_EXPENSE_AMT_ = _ANNUAL_EXPENSE_AMT_;
  _SP_PARAM_ANNUAL_EXPENSE_OTH_AMT_ = _ANNUAL_EXPENSE_OTH_AMT_;
  _SP_PARAM_ANNUAL_DEBT_AMT_ = _ANNUAL_DEBT_AMT_;
  _SP_PARAM_ANNUAL_PROFIT_AMT_ = _ANNUAL_PROFIT_AMT_;
  _SP_PARAM_EMPLOYEE_TOTAL_NO_ = _EMPLOYEE_TOTAL_NO_;
  _SP_PARAM_REF_DOC_NO_ = _REF_DOC_NO_;
  _SP_PARAM_REF_DOC_DATE_ = _REF_DOC_DATE_;
  _SP_PARAM_REF_ISSUE_BY_ = _REF_ISSUE_BY_;
  _SP_PARAM_EMAIL_ADDRESS_ = _EMAIL_ADDRESS_;
  _SP_PARAM_REAL_ESTATE_LAND_AMT_ = _REAL_ESTATE_LAND_AMT_;
  _SP_PARAM_REAL_ESTATE_OTH_AMT_ = _REAL_ESTATE_OTH_AMT_;
  _SP_PARAM_PD_GRADE_SCORE_ = _PD_GRADE_SCORE_;
  _SP_PARAM_PD_GRADE_INIT_SCORE_DATE_ = _PD_GRADE_INIT_SCORE_DATE_;
  _SP_PARAM_PD_GRADE_REVISED_SCORE_DATE_ = _PD_GRADE_REVISED_SCORE_DATE_;
  _SP_PARAM_REG_IN_STOCK_EXCHANGE_MARKET_ = _REG_IN_STOCK_EXCHANGE_MARKET_;
  _SP_PARAM_MOST_INCOME_IN_CASH_ = _MOST_INCOME_IN_CASH_;

  {***** Personal Info params *****}
  _SP_PARAM_PERSON_LEGAL_TYPE_ = _PERSON_LEGAL_TYPE_;
  _SP_PARAM_CITIZENSHIP_ = _CITIZENSHIP_;
  _SP_PARAM_NATIONALITY_ = _NATIONALITY_;
  _SP_PARAM_BIRTH_DATE_ = _BIRTH_DATE_;
  _SP_PARAM_GENDER_ = _GENDER_;
  _SP_PARAM_EDUCATION_ = _EDUCATION_;
  _SP_PARAM_MARRIED_STATUS_ = _MARRIED_STATUS_;
  _SP_PARAM_OCCUPATION_ = _OCCUPATION_;
  _SP_PARAM_WORK_PLACE_ = _WORK_PLACE_;
  _SP_PARAM_WORK_TYPE_ = _WORK_TYPE_;
  _SP_PARAM_JOB_POSITION_ = _JOB_POSITION_;
  _SP_PARAM_WORK_BUS_TYPE_ = _WORK_BUS_TYPE_;
  _SP_PARAM_CONTACT_PERSON_TITLE_NAME_ = _CONTACT_PERSON_TITLE_NAME_;
  _SP_PARAM_CONTACT_PERSON_FIRST_NAME_ = _CONTACT_PERSON_FIRST_NAME_;
  _SP_PARAM_CONTACT_PERSON_LAST_NAME_ = _CONTACT_PERSON_LAST_NAME_;
  _SP_PARAM_CONTACT_PERSON_RELATION_ = _CONTACT_PERSON_RELATION_;
  _SP_PARAM_CONTACT_PERSON_MOBILE_PHONE_ = _CONTACT_PERSON_MOBILE_PHONE_;
  _SP_PARAM_MOBILE_NO_ = _MOBILE_NO_;
  //_SP_PARAM_EMAIL_ADDRESS_ = _EMAIL_ADDRESS;
  _SP_PARAM_HAS_NAME_CHANGED_HISTORY_ = _HAS_NAME_CHANGED_HISTORY_;
  _SP_PARAM_NAME_CHANGED_REASON_ = _NAME_CHANGED_REASON_;

  {***** Co-operated params *****}
  _SP_PARAM_NOTE_ = _NOTE_;
  _SP_PARAM_NEW_CIF_ID_ = _NEW_CIF_ID_;
  _SP_PARAM_NEW_CIF_NO_ = _NEW_CIF_NO_;
  _SP_PARAM_ACCOUNT_ID_ = _ACCOUNT_ID_;
  _SP_PARAM_NEW_ACCOUNT_ID_ = _NEW_ACCOUNT_ID_;

  {***** Parameter for SP_CIF_ADR_SET_ITEM_BY_ID *****}
  _ADDRESS_GROUP_ = 'ADDRESS_GROUP';
  _ADDRESS_ID_ = 'ADDRESS_ID';
  _ADDR_LINE_01_ = 'ADDR_LINE_01';
  _ADDR_LINE_02_ = 'ADDR_LINE_02';
  _ADDR_LINE_03_ = 'ADDR_LINE_03';
  _ADDR_LINE_04_ = 'ADDR_LINE_04';
  _AMPHUR_ = 'AMPHUR';
  _PROVINCE_ = 'PROVINCE';
  _POST_CODE_ = 'POST_CODE';
  _TEL_NO_ = 'TEL_NO';
  _FAX_NO_ = 'FAX_NO';
  _RESIDENT_YEAR_ = 'RESIDENT_YEAR';
  _OWNER_STATUS_ = 'OWNER_STATUS';
  _ADDRESS_LIKE_ = 'ADDRESS_LIKE';

  _SP_PARAM_ADDRESS_GROUP_ = _ADDRESS_GROUP_;
  _SP_PARAM_ADDRESS_ID_ = _ADDRESS_ID_;
  _SP_PARAM_ADDR_LINE_01_ = _ADDR_LINE_01_;
  _SP_PARAM_ADDR_LINE_02_ = _ADDR_LINE_02_;
  _SP_PARAM_ADDR_LINE_03_ = _ADDR_LINE_03_;
  _SP_PARAM_ADDR_LINE_04_ = _ADDR_LINE_04_;
  _SP_PARAM_AMPHUR_ = _AMPHUR_;
  _SP_PARAM_PROVINCE_ = _PROVINCE_;
  _SP_PARAM_POST_CODE_ = _POST_CODE_;
  _SP_PARAM_TEL_NO_ = _TEL_NO_;
  _SP_PARAM_FAX_NO_ = _FAX_NO_;
  _SP_PARAM_RESIDENT_YEAR_ = _RESIDENT_YEAR_;
  _SP_PARAM_OWNER_STATUS_ = _OWNER_STATUS_;
  _SP_PARAM_ADDRESS_LIKE_ = _ADDRESS_LIKE_;

  {****** Begin: MS SQL Server Synchronization constants ******}
  {***** For each process of any action *****}
{$IFNDEF MSSQL_DIALECT}
  _SYNC_UPDATE_SQL_: array[0..2] of String = (
    'SELECT STR_VALUE FROM SP_SYNC_INSERT_STATEMENT(%d)',
    'SELECT STR_VALUE FROM SP_SYNC_UPDATE_STATEMENT(%d)',
    'SELECT STR_VALUE FROM SP_SYNC_DELETE_STATEMENT(%d)');

  _SYNC_DELETE_REC_ = 'SELECT RESULT FROM SP_SYNC_DEL_REC(%d)';

  {***** All *****}
  _SYNC_ALL_META_DATA_ = 'SELECT * FROM SP_SYNC_GET_META_DATA';
  _SYNC_SQL_STATEMENT_ = 'SQL_STATEMENT';
  _SYNC_DESCRIPTION_ = 'DESCRIPTION';


  _SYNC_ALL_INIT_SRC_DATA_ = 'EXECUTE PROCEDURE SP_SYNC_INIT_ID';
  _SYNC_ALL_SELECT_SRC_DATA_ = 'SELECT * FROM %s';
  _SYNC_ALL_DEL_TARGET_ = 'DELETE FROM %s';

  _SYNC_ALL_DEL_LOG_ = 'DELETE FROM TTSYNC_LOG';
  _SYNC_ALL_INIT_LOG_ = 'ALTER SEQUENCE SQ_SYNC_ID RESTART WITH 0';
{$ENDIF}
  {****** End: MS SQL Server Synchronization constants ******}


  {******************* Roles/Users Management *******************}
  _SEARCH_ROLE_BY_REC_ID_ = 'RECORD_ID = %d';
  _SEARCH_USER_BY_REC_ID_ =  _SEARCH_ROLE_BY_REC_ID_;

//  _DELETE_ROLE_BY_REC_ID_ =  'DELETE FROM BTCT_ROLES WHERE (RECORD_ID = %d)';
//  _DELETE_USER_BY_REC_ID_ =  'DELETE FROM BTCT_USERS WHERE (RECORD_ID = %d)';

  _ROLE_REC_ID_ = 'ROLE_REC_ID';

  _STATUS_FLAG_ = 'STATUS_FLAG';

  _USER_REC_ID_ = 'USER_REC_ID';
  _ORG_CODE_ = 'ORG_CODE';
  _OFFICER_ID_ = 'OFFICER_ID';
  _USER_POSITION_ = 'USER_POSITION';
  _OFFICER_TYPE_ = 'OFFICER_TYPE';
  _VALID_FROM_ = 'VALID_FROM';
  _VALID_THRU_ = 'VALID_THRU';
  _RALEASE_SUSPENDED_DATE_ = 'RALEASE_SUSPENDED_DATE';

  _IS_LOGGED_ = 'IS_LOGGED';

  _SP_PARAM_ROLE_REC_ID_ = _ROLE_REC_ID_;

  _SP_PARAM_STATUS_FLAG_ = _STATUS_FLAG_;
  _SP_PARAM_ROLE_ID_ = _ROLE_ID_;

  _SP_PARAM_USER_REC_ID_ = _USER_REC_ID_;
  _SP_PARAM_ORG_CODE_ = _ORG_CODE_;
  _SP_PARAM_OFFICER_ID_ = _OFFICER_ID_;
  _SP_PARAM_USER_PWD_ = _USER_PWD_;
  _SP_PARAM_USER_POSITION_ = _USER_POSITION_;
  _SP_PARAM_OFFICER_TYPE_ = _OFFICER_TYPE_;
  _SP_PARAM_VALID_FROM_ = _VALID_FROM_;
  _SP_PARAM_VALID_THRU_ = _VALID_THRU_;
  _SP_PARAM_RALEASE_SUSPENDED_DATE_ = _RALEASE_SUSPENDED_DATE_;

  _SP_PARAM_IS_LOGGED_ = _IS_LOGGED_;

  {******************* Menues/Objects Management *******************}
  _PARENT_APP_ID_ = 'PARENT_APP_ID';
  _PARENT_FORM_ID_ = 'PARENT_FORM_ID';

  _COMPONENT_ID_ = 'COMPONENT_ID';
  _IS_ENABLED_ = 'IS_ENABLED';
  _IS_VISIBLED_ = 'IS_VISIBLED';
  _IS_APPLICATION_ = 'IS_APPLICATION';

  _APP_NAME_ = 'APP_NAME';
  _FORM_NAME_ = 'FORM_NAME';
  _PARENT_NAME_ = 'PARENT_NAME';
  _COMPONENT_CLASS_ = 'COMPONENT_CLASS';
  _COMPONENT_NAME_ = 'COMPONENT_NAME';
  _COMPONENT_DESC_ = 'COMPONENT_DESC';

  _SP_PARAM_PARENT_APP_ID_ = _PARENT_APP_ID_;
  _SP_PARAM_PARENT_FORM_ID_ = _PARENT_FORM_ID_;

  _SP_PARAM_COMPONENT_ID_ = _COMPONENT_ID_;
  _SP_PARAM_IS_ENABLED_ = _IS_ENABLED_;
  _SP_PARAM_IS_VISIBLED_ = _IS_VISIBLED_;
  _SP_PARAM_IS_APPLICATION_ = _IS_APPLICATION_;

  _SP_PARAM_APP_NAME_ = _APP_NAME_;
  _SP_PARAM_FORM_NAME_ = _FORM_NAME_;
  _SP_PARAM_PARENT_NAME_ = _PARENT_NAME_;
  _SP_PARAM_COMPONENT_CLASS_ = _COMPONENT_CLASS_;
  _SP_PARAM_COMPONENT_NAME_ = _COMPONENT_NAME_;
  _SP_PARAM_COMPONENT_DESC_ = _COMPONENT_DESC_;

  _SQL_GET_PASSWORD_AGE_ =
    'SELECT CAST(D.AMT_1 AS INTEGER) AS RESULT FROM BTCT_ST_DTL D ' +
    'WHERE (D.ABBR_HEADER_CODE = ''PWD_AGE'') AND (D.DETAIL_CODE = ''AGE'')';

  _SQL_SET_PASSWORD_AGE_ =
    'UPDATE BTCT_ST_DTL D SET D.AMT_1 = %d ' +
    'WHERE (D.ABBR_HEADER_CODE = ''PWD_AGE'') AND (D.DETAIL_CODE = ''AGE'')';

  _SQL_RELEASE_ALL_LOCKED_USER_ =
    'UPDATE BTCT_USERS SET STATUS = 1000000 WHERE (STATUS = 1000020)';

{$IFDEF MSSQL_DIALECT}
  _SQL_CLEAR_TEMP_ =
    'EXEC SP_TMP_CLEAR';
{$ELSE}
  _SQL_CLEAR_TEMP_ =
    'EXECUTE PROCEDURE SP_TMP_CLEAR';
{$ENDIF}


var
  _SERVER_VERSION:string;

implementation

end.
